/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/get-public-download-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Getpublicdownloadlist */
        get: operations["GetPublicDownloadList_api_get_public_download_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Getdownloadlistbyid */
        get: operations["GetDownloadListById_api__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/create_download_list_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_api_create_download_list_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateDownloadListDto */
        CreateDownloadListDto: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Author */
            author: string;
            /** Ui Type */
            ui_type: string;
            /** Downloaded List */
            downloaded_list: components["schemas"]["DownloadListBodyDto"][];
            /** Ispublic */
            isPublic: boolean;
        };
        /** CreateDownloadListResponseDto */
        CreateDownloadListResponseDto: {
            /** Url */
            url: string;
        };
        /** DownloadListBodyDto */
        DownloadListBodyDto: {
            /** Model Id */
            model_id: number | null;
            /** Source */
            source: string;
            /** Type */
            type: string | null;
            /** Basemodel */
            baseModel: string | null;
            /** Name */
            name: string;
            /** Version */
            version: string | null;
            /** Modellink */
            modellink: string;
            /** Filename */
            fileName: string;
            /** Downloadurl */
            downloadUrl: string;
            previewImage: components["schemas"]["ImagePreviewDto"] | null;
            /** Downloadmodeltype */
            DownloadModelType: string;
        };
        /** DownloadListResponseDto */
        DownloadListResponseDto: {
            /**  Id */
            _id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Author */
            author: string;
            /** Ui Type */
            ui_type: string;
            /** Download List */
            download_list: components["schemas"]["DownloadListBodyDto"][];
            /** Ispublic */
            isPublic: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Deletedat */
            deletedAt: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePreviewDto */
        ImagePreviewDto: {
            /** Url */
            url: string;
            /** Nsfwlevel */
            nsfwLevel: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Hash */
            hash: string;
            /** Type */
            type: string;
        };
        /** PublicDownloadListResponseDto */
        PublicDownloadListResponseDto: {
            /** Data */
            data: components["schemas"]["DownloadListResponseDto"][];
            /** Total Items */
            total_items: number;
            /** Current Page */
            current_page: number;
            /** Total Pages */
            total_pages: number;
            /** Page Size */
            page_size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetPublicDownloadList_api_get_public_download_list_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDownloadListResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    GetDownloadListById_api__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadListResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_create_download_list_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDownloadListDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDownloadListResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
